"""empty message

Revision ID: 31c6e29748eb
Revises: 5a16c2d4cef1
Create Date: 2018-04-22 04:53:41.421145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c6e29748eb'
down_revision = '5a16c2d4cef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_origins_resource'), 'origins', ['resource'], unique=True)
    op.drop_index('ix_origins_name', table_name='origins')
    op.create_index(op.f('ix_origins_name'), 'origins', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_origins_name'), table_name='origins')
    op.create_index('ix_origins_name', 'origins', ['name'], unique=False)
    op.drop_index(op.f('ix_origins_resource'), table_name='origins')
    # ### end Alembic commands ###
