"""empty message

Revision ID: 5a96e91f3227
Revises: 31c6e29748eb
Create Date: 2018-04-22 05:10:45.961406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a96e91f3227'
down_revision = '31c6e29748eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_resource_name_uc', 'origins', ['resource', 'name'])
    op.drop_index('ix_origins_name', table_name='origins')
    op.create_index(op.f('ix_origins_name'), 'origins', ['name'], unique=False)
    op.drop_index('ix_origins_resource', table_name='origins')
    op.create_index(op.f('ix_origins_resource'), 'origins', ['resource'], unique=False)
    op.alter_column('user_groups', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('_user_group_uc', 'user_groups', ['user_id', 'group_id'])
    op.drop_constraint('user_groups_group_id_key', 'user_groups', type_='unique')
    op.drop_constraint('user_groups_user_id_key', 'user_groups', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_groups_user_id_key', 'user_groups', ['user_id'])
    op.create_unique_constraint('user_groups_group_id_key', 'user_groups', ['group_id'])
    op.drop_constraint('_user_group_uc', 'user_groups', type_='unique')
    op.alter_column('user_groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_groups', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_origins_resource'), table_name='origins')
    op.create_index('ix_origins_resource', 'origins', ['resource'], unique=True)
    op.drop_index(op.f('ix_origins_name'), table_name='origins')
    op.create_index('ix_origins_name', 'origins', ['name'], unique=True)
    op.drop_constraint('_resource_name_uc', 'origins', type_='unique')
    # ### end Alembic commands ###
