"""empty message

Revision ID: 6910962b4359
Revises: 742e00ad29fb
Create Date: 2018-04-28 23:14:32.996651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6910962b4359'
down_revision = '742e00ad29fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_channels_name', table_name='user_channels')
    op.drop_constraint('user_channels_group_id_fkey', 'user_channels', type_='foreignkey')
    op.drop_column('user_channels', 'name')
    op.drop_column('user_channels', 'group_id')
    op.drop_constraint('_user_group_uc', 'user_groups', type_='unique')
    op.drop_column('user_groups', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint('_user_group_uc', 'user_groups', ['user_id', 'group_id'])
    op.add_column('user_channels', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_channels', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_foreign_key('user_channels_group_id_fkey', 'user_channels', 'user_groups', ['group_id'], ['id'])
    op.create_index('ix_user_channels_name', 'user_channels', ['name'], unique=True)
    # ### end Alembic commands ###
