"""empty message

Revision ID: 742e00ad29fb
Revises: 386b3692919d
Create Date: 2018-04-24 23:32:37.657605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742e00ad29fb'
down_revision = '386b3692919d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epgs', sa.Column('_arts', sa.Text(), nullable=True))
    op.drop_column('epgs', 'arts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epgs', sa.Column('arts', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('epgs', '_arts')
    # ### end Alembic commands ###
